name: system_properties
description: flutter plugin for getting system properties easily for android.
version: 1.0.0
homepage: https://github.com/anuoua/system_properties.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.system_properties
        pluginClass: SystemPropertiesPlugin
      ios:
        pluginClass: SystemPropertiesPlugin